### ISSUE TITLE
Link within a layout?

### ISSUE THREAD

**Issue by lawtj** [gabrieltempass/streamlit-navigation-bar#1]
### Checklist

- [X] I have read the documentation at [README.md](https://github.com/gabrieltempass/streamlit-navigation-bar/blob/main/README.md).

### Add a description

Great package, have been exploring and I think it'll do the trick for me!

One question - in my main landing page, I'd like to include links to other pages in the app. Is there a suggested workflow for this? I tried `st_button(label='about page', on_click=pg.show_about)` for instance, but it didn't work/didn't keep the nav bar.

**Comment by gabrieltempass** [comment]
Hi @lawtj, thanks for your question!

Currently there are two main ways to use `st_navbar` with a multipage app (MPA):

1. The first one is when the app follows [Streamlit's MPA](https://docs.streamlit.io/library/advanced-features/multipage-apps) structure. Which I believe is your case, right? If it is, you will need to call the `st_navbar()` function at the top of every `.py` file inside the `pages` directory, in order for the navbar to appear when you switch pages.

This approach is the more intuitive one, since it uses Streamlit's oficial solution for MPA. However, when you click to switch to another page, the navbar will disappear for some milliseconds and reappear. Causing a really bad user experience. And at the moment I still don't know how to get rid of this.

I know that the Streamlit team will soon release a [new API for MPA](https://github.com/streamlit/streamlit/issues/8388). Maybe then I can make `st_navbar` work more seamlessly with this approach.

2. The second way is demonstrated in this example in the documentation:

> An example using a logo, an external URL, multiple pages with content, among
> other things:
> ``` python
> import os
> import streamlit as st
> from streamlit_navigation_bar import st_navbar
> import pages as pg
> 
> st.set_page_config(initial_sidebar_state="collapsed")
> 
> pages = ["Install", "User Guide", "API", "Examples", "Community", "GitHub"]
> parent_dir = os.path.dirname(os.path.abspath(__file__))
> logo_path = os.path.join(parent_dir, "cubes.svg")
> urls = {"GitHub": "https://github.com/gabrieltempass/streamlit-navigation-bar"}
> styles = {
>     "nav": {
>         "background-color": "royalblue",
>         "justify-content": "left",
>     },
>     "img": {
>         "padding-right": "14px",
>     },
>     "span": {
>         "color": "white",
>         "padding": "14px",
>     },
>     "active": {
>         "color": "var(--text-color)",
>         "background-color": "white",
>         "font-weight": "normal",
>         "padding": "14px",
>     }
> }
> 
> page = st_navbar(
>     pages,
>     logo_path=logo_path,
>     urls=urls,
>     styles=styles,
>     options=False,
> )
> 
> functions = {
>     "Home": pg.show_home,
>     "Install": pg.show_install,
>     "User Guide": pg.show_user_guide,
>     "API": pg.show_api,
>     "Examples": pg.show_examples,
>     "Community": pg.show_community,
> }
> go_to = functions.get(page)
> if go_to:
>     go_to()
> ```
> [![Example 3](https://github.com/gabrieltempass/streamlit-navigation-bar/raw/main/images/st_navbar_3.gif)](https://st-navbar-3.streamlit.app/)
> [**[App]**](https://st-navbar-3.streamlit.app/) [**[Source]**](https://github.com/gabrieltempass/streamlit-navigation-bar/blob/main/examples/st_navbar_3/streamlit_app.py)

The major difference is that the content of each page must be inside a function, which will be called from your main `.py` file. For example, check how the content from the Community page is inside the [`show_community()`](https://github.com/gabrieltempass/streamlit-navigation-bar/blob/cf27fa6ad4d5c5644482695fc1ab0e20be92d530/examples/st_navbar_3/pages/community.py#L4) function from [`community.py`](https://github.com/gabrieltempass/streamlit-navigation-bar/blob/cf27fa6ad4d5c5644482695fc1ab0e20be92d530/examples/st_navbar_3/pages/community.py#L4). Also, don't forget that you will have to import these functions in your main file.

As you would imagine, this approach has some downsides. Like not being able to access a specific page of your app via its URL (e.g. https://st-navbar-3.streamlit.app/community). But the navbar won't briefly disappear when switching pages, so right now I would recommend this path.

I hope that helps you!

**Comment by gabrieltempass** [comment]
@lawtj I created a page in the documentation to explain this in more detail:

https://github.com/gabrieltempass/streamlit-navigation-bar/wiki/Multipage
